### PR TITLE
Fixes #13 generated thrift code at 808d143245f is returning err here

### LINKED ISSUE #13: multiple-value tFac.GetTransport() in single-value context when building against code generated by latest thrift (808d143245f)
This is the version of thrift I used to generate the go code:
```
$ git rev-parse HEAD
808d143245f4f5c30600fab31cf9db854cbf5b48
```

This is the error I get when I compile the load test example:
```
# github.com/pinterest/bender/thrift
src/github.com/pinterest/bender/thrift/thrift.go:41: multiple-value tFac.GetTransport() in single-value context
```

PR incoming.

### PR DESCRIPTION
**Pull request by dbravender**

### CODE REVIEW

**Comment by insomniacslk** [comment]
seems like this PR has been stuck for over a year - worth recreating it with tests?

**Comment by insomniacslk** [comment]
at a second glance, and as per @earlgreyz comment, there is no test at all for thrift, and the fact that the build otherwise fails without this patch should be a good enough indicator

**Comment by insomniacslk** [comment]
CC @dbravender

**Comment by insomniacslk** [comment]
cc @nichochar

**Comment by jparise** [comment]
Sorry for the delay on this. Merged as 9efd31e.

**Pull request merged**
