### PR TITLE
[dhcpv4] fix build

### PR DESCRIPTION
**Pull request by pmazzini**
Fix build after https://github.com/insomniacslk/dhcp/pull/223.

### CODE REVIEW

**Comment by pmazzini** [comment]
Travis failure is not related to this PR.

**Comment by jparise** [comment]
Your change looks good, but I'd prefer to fix the unrelated error first so we can get a clear CI pass for landing this PR.

If you're able to submit a fix for that issue, we'd appreciate it. Otherwise, I'll try to look into it myself in the next few days.

**Comment by pmazzini** [comment]
I think the dns library was not compiling with go 1.9. I updated the travis config.

**Comment by jparise** [comment]
> I think the dns library was not compiling with go 1.9. I updated the travis config.

Ah, I see. Thanks!

It's too bad we've lost go1.9 (and earlier) compatibility, but we can revisit that if there's a need.

**Pull request merged**
